### ISSUE TITLE
QR code dialoge / window disappears after some seconds

### ISSUE THREAD

**Issue by samuelhurni** [Twint-AG/twint-woocommerce-extension#1]
I face some torubles by using the twint plugin for WooCommerce. Installation worked and also set up with the custom credentials. Button for express checkout and normal checkout is also there.

If I click on the Express checkout button, a dialoge opens also with the qr code and twint checkout. But this dialoge closes after approx. 5s before the payment can be done. Also when I was able to scan the code with my twint app, in the Twint App appears the message: "To process this code, you must first update your TWINT app. please check wheter an update is available". But there is no update on the IOS appstore available.

Using Wordpress 6.6.2
Php Version 8.1
Soap is installed.
Checking Credentials in the Twint Section in Wordpress was ok.

**Comment by lstrojny** [comment]
Thank you for the report. The issue should be resolved in [1.0.0-RC22](https://github.com/Twint-AG/twint-woocommerce-extension/releases/tag/1.0.0-RC22)

**Comment by samuelhurni** [comment]
Hi Lars Ok I tested it an the first Issue: Link is now solved for me as well. Do you know when you plan to look towards the second Issue: Link with the direct payment order view, which is not working? This is really essential for my shop to go online because I have some custom functions that need to be handled like that.  Regards Samuel  From: Lars Strojny ***@***.***>Date: Wednesday, 13 November 2024 at 14:35To: Twint-AG/twint-woocommerce-extension ***@***.***>Cc: samuelhurni ***@***.***>, Author ***@***.***>Subject: Re: [Twint-AG/twint-woocommerce-extension] QR code dialoge / window disappears after some seconds (Issue #1)Thank you for the report. The issue should be resolved in 1.0.0-RC22—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
